ERROR io_services_utils.py:796 Socket EOF; <socket.socket fd=13, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 51258, 0, 0), raddr=('::1', 5672, 0, 0)>
ERROR base_connection.py:445 Transport indicated EOF.
ERROR base_connection.py:428 connection_lost: StreamLostError: ('Transport indicated EOF',)
ERROR blocking_connection.py:521 Unexpected connection close detected: StreamLostError: ('Transport indicated EOF',)
ERROR _server.py:453 Exception calling application: module 'docker' has no attribute 'DockerClient'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 75, in get_container_status
    client = docker.DockerClient()
AttributeError: module 'docker' has no attribute 'DockerClient'
ERROR _server.py:453 Exception calling application: module 'docker' has no attribute 'DockerClient'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 75, in get_container_status
    client = docker.DockerClient()
AttributeError: module 'docker' has no attribute 'DockerClient'
ERROR _server.py:453 Exception calling application: 'function' object has no attribute 'get'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 78, in get_container_status
    container = client.containers.get(container_name_or_id)
AttributeError: 'function' object has no attribute 'get'
ERROR _server.py:453 Exception calling application: module 'docker' has no attribute 'DockerClient'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 75, in get_container_status
    client = docker.DockerClient()
AttributeError: module 'docker' has no attribute 'DockerClient'
ERROR _server.py:453 Exception calling application: module 'docker' has no attribute 'DockerClient'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 75, in get_container_status
    client = docker.DockerClient()
AttributeError: module 'docker' has no attribute 'DockerClient'
ERROR _server.py:453 Exception calling application: 'function' object has no attribute 'get'
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 42, in GetInstanceInfo
    status = docker_utils.get_container_status(request.instance_id)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 78, in get_container_status
    container = client.containers.get(container_name_or_id)
AttributeError: 'function' object has no attribute 'get'
ERROR _server.py:453 Exception calling application: {'message': 'invalid reference format'}
Traceback (most recent call last):
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/server/instance_server.py", line 34, in CreateImage
    image = docker_utils.build_image(image_to_build_path, f"{request.repository}:{request.tag}")
  File "/Users/chenxingyang/PycharmProjects/0049-server-python/app/utils/docker_utils.py", line 9, in build_image
    image, build_logs = client.images.build(path=dockerfile_path, tag=tag)
  File "/Users/chenxingyang/opt/anaconda3/envs/flask/lib/python3.8/site-packages/docker/models/images.py", line 317, in build
    raise BuildError(last_event or 'Unknown', result_stream)
docker.errors.BuildError: {'message': 'invalid reference format'}
